version: "3"
services:

    lee-server:
        build: .
        container_name: "lee-server"
        ports:
            - 4000:4000
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        command: mongod